[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret='4e2cb1e64e0e184a4f98e0d27e6a1ef779022a1b62e9c636f560e9cc94a7ccdf'

[auth.auth0]
domain='http://dev-1yjtdfcmy4tkj356.us.auth0.com'
client_id = "IR98UpmkZ1S4tDD6pvouXixDiBjZLc04"
client_secret = "Vhjc0abqiTchACB1aMs0ZwTCaO4rUm-XEP1szkEMbktahvucBxKvgyA80EgywAji"
server_metadata_url="https://<DOMAIN>.<REGION>.auth0.com/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }